version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${REPO_ECR}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $REPOSITORY_URI:latest
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "========= Connect to EKS ============"
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name ${EKS_CLUSTER}
      - echo "========== Assume role ======"
      - kubectl get pods -o wide
      #- CREDS=$(aws sts assume-role --role-arn arn:aws:sts::925900902386:assumed-role/codebuild-SpringBootProject-service-role --role-session-name "CodeBuild" --duration-seconds 1800)
      #- AWS_ACCESS_KEY_ID="$(echo $CREDS | jq -r '.Credentials.AccessKeyId')"
      #- AWS_SECRET_ACCESS_KEY="$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')"
      #- AWS_SESSION_TOKEN="$(echo $CREDS | jq -r '.Credentials.SessionToken')"
      #- AWS_EXPIRATION=$(echo $CREDS | jq -r '.Credentials.Expiration')
      #- kubectl get pods -o wide
